### ISSUE TITLE
Your constrastive divergence

### ISSUE THREAD

**Issue by daokiemhydra0851** [GabrielBianconi/pytorch-rbm#1]
Explain algorithm pls , i dont get it. This is RBM for real number, why you use Sigmoid ?

**Comment by GabrielBianconi** [comment]
This implementation is a binary (Bernoulli) RBM. The input data is in the [0, 1] range, and can be interpreted as probabilities. The final output is also probabilities. For further reference, see

-https://www.cs.toronto.edu/~hinton/absps/guideTR.pdf
- http://www.cs.toronto.edu/~hinton/science.pdf

I recently updated the code with other changes. If you see any other issues, please let me know.
